#!/usr/bin/env python3
"""Sign Lab 10 firmware images (Ed25519) and manage the signing key.

    pip install cryptography

    # once: make a key pair and the C header the bootloader embeds
    fw_sign.py keygen --key tools/keys/demo_ed25519.pem \
                      --header modules/10-bootloaders-updates/lab/common/pubkey.h

    # per build: wrap the application binary (linked for slot A or B) in a signed header
    fw_sign.py sign --key tools/keys/demo_ed25519.pem --bin app_slot_a.bin \
                    --version 1.2.0 --counter 3 --slot A --out app_slot_a.signed.bin

Signature = Ed25519(SHA-512(header_without_signature || payload)), matching
modules/10-bootloaders-updates/lab/common/image.h.
"""
import argparse
import hashlib
import struct
import sys

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
except ImportError:
    sys.exit("the 'cryptography' package is required: pip install cryptography")

IMAGE_MAGIC = 0x31474D49
HEADER_SIZE = 0x400
SIG_SIZE = 64


def load_key(path: str) -> Ed25519PrivateKey:
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def cmd_keygen(args) -> int:
    key = Ed25519PrivateKey.generate()
    pem = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                            serialization.NoEncryption())
    with open(args.key, "wb") as f:
        f.write(pem)
    write_header(key, args.header)
    print(f"wrote {args.key} and {args.header}")
    return 0


def write_header(key: Ed25519PrivateKey, path: str) -> None:
    pub = key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    body = ",\n    ".join(", ".join(f"0x{b:02x}" for b in pub[i:i + 8]) for i in range(0, 32, 8))
    with open(path, "w", encoding="ascii") as f:
        f.write(
            "/* Generated by tools/fw_sign.py keygen. Ed25519 public key of the image signer.\n"
            " * DEMO KEY: its private half is in the course repository. Never ship it. */\n"
            "#ifndef PUBKEY_H\n#define PUBKEY_H\n\n#include <stdint.h>\n\n"
            f"static const uint8_t k_signer_pubkey[32] = {{\n    {body},\n}};\n\n#endif\n")


def parse_version(v: str) -> int:
    major, minor, patch = (int(x) for x in v.split("."))
    if not (0 <= major < 65536 and 0 <= minor < 256 and 0 <= patch < 256):
        raise ValueError("version out of range")
    return (major << 16) | (minor << 8) | patch


def cmd_sign(args) -> int:
    key = load_key(args.key)
    payload = open(args.bin, "rb").read()
    slot = {"A": 0, "B": 1}[args.slot.upper()]
    fixed = struct.pack("<6I", IMAGE_MAGIC, HEADER_SIZE, len(payload), parse_version(args.version),
                        args.counter, slot)
    header_wo_sig = fixed + b"\xff" * (HEADER_SIZE - SIG_SIZE - len(fixed))
    digest = hashlib.sha512(header_wo_sig + payload).digest()
    signature = key.sign(digest)
    with open(args.out, "wb") as f:
        f.write(header_wo_sig + signature + payload)
    print(f"{args.out}: v{args.version} counter {args.counter} slot {args.slot.upper()}, "
          f"{len(payload)} bytes payload")
    return 0


def cmd_header(args) -> int:
    write_header(load_key(args.key), args.header)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    k = sub.add_parser("keygen")
    k.add_argument("--key", required=True)
    k.add_argument("--header", required=True)
    h = sub.add_parser("pubkey-header", help="regenerate pubkey.h from an existing key")
    h.add_argument("--key", required=True)
    h.add_argument("--header", required=True)
    s = sub.add_parser("sign")
    s.add_argument("--key", required=True)
    s.add_argument("--bin", required=True)
    s.add_argument("--version", required=True, help="major.minor.patch")
    s.add_argument("--counter", type=int, required=True, help="security (anti-rollback) counter")
    s.add_argument("--slot", required=True, choices=["A", "B", "a", "b"])
    s.add_argument("--out", required=True)
    args = ap.parse_args()
    return {"keygen": cmd_keygen, "sign": cmd_sign, "pubkey-header": cmd_header}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
