#!/usr/bin/env python3
"""Generate the device-interrupt part of a vector table from a CMSIS device header.

Usage: gen_vectors.py <stm32xxxx.h> <output.h>

The output is an X-macro list, one line per vector slot from IRQ 0 to the
highest IRQ number in the header's IRQn_Type enum:

    VECTOR(WWDG_IRQHandler)        /* 0 */
    RESERVED()                     /* 1: not implemented on this device */

startup files define VECTOR and RESERVED, then #include the list. Reading
the slot order straight from the vendor header avoids the classic bug of a
hand-typed vector table that is off by one entry.
"""
import re
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    header, out = sys.argv[1], sys.argv[2]
    text = open(header, encoding="utf-8", errors="replace").read()
    enum = re.search(r"typedef enum\s*\{(.*?)\}\s*IRQn_Type", text, re.S)
    if not enum:
        print(f"no IRQn_Type enum found in {header}", file=sys.stderr)
        return 1
    irqs = {}
    for name, value in re.findall(r"^\s*(\w+)_IRQn\s*=\s*(-?\d+)", enum.group(1), re.M):
        if int(value) >= 0:
            irqs[int(value)] = name
    lines = [
        f"/* Generated by tools/gen_vectors.py from {header.split('/')[-1]}. Do not edit. */",
    ]
    for n in range(max(irqs) + 1):
        if n in irqs:
            lines.append(f"VECTOR({irqs[n]}_IRQHandler) /* {n} */")
        else:
            lines.append(f"RESERVED() /* {n} */")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
